using System.ComponentModel.DataAnnotations;

namespace AceJobAgency.ViewModels
{
    public class LoginViewModel
    {
        [Required, EmailAddress]
        public string Email { get; set; } = "";

        [Required]
        public string Password { get; set; } = "";

        // reCAPTCHA token generated by client-side grecaptcha.execute
        public string RecaptchaToken { get; set; } = "";
    }
}
